# This is a basic workflow to help you get started with Actions
name: first-workflow
# Controls when the workflow will run
on: workflow_dispatch 
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: first-job
        run: echo”hi”
      - name: print hello
        run: echo”bye”
